global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'product-service'
    metrics_path: '/product-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8500']

  - job_name: 'user-service'
    metrics_path: '/user-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8700']

  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8300']

  - job_name: 'payment-service'
    metrics_path: '/payment-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8400']